//
//  LR35902Execution.swift
//  GBEmu
//
//  Created by Jacob Ertell on 4/27/23.
//

import Foundation

extension CPU {
    func evaluate(_ instruction: LR35902Instruction) throws {
        switch instruction {
            case .nop:
                try nop()
            case .ld_BC_d16:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_BCptr_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .inc_BC:
                throw LR35902ExecutionError.instructionNotImplemented
            case .inc_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .dec_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_B_d8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rcla:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_a16ptr_SP:
                throw LR35902ExecutionError.instructionNotImplemented
            case .add_HL_BC:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_A_BCptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .dec_BC:
                throw LR35902ExecutionError.instructionNotImplemented
            case .inc_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .dec_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_C_d8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rrca:
                throw LR35902ExecutionError.instructionNotImplemented
            case .stop:
                try stop()
            case .ld_DE_d16:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_DEptr_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .inc_DE:
                throw LR35902ExecutionError.instructionNotImplemented
            case .inc_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .dec_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_D_d8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rla:
                throw LR35902ExecutionError.instructionNotImplemented
            case .jr_s8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .add_HL_DE:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_A_DEptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .dec_DE:
                throw LR35902ExecutionError.instructionNotImplemented
            case .inc_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .dec_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_E_d8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rra:
                throw LR35902ExecutionError.instructionNotImplemented
            case .jr_nz_s8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_HL_d16:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_HLptrInc_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .inc_HL:
                throw LR35902ExecutionError.instructionNotImplemented
            case .inc_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .dec_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_H_d8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .daa:
                try daa()
            case .jr_z_s8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .add_HL_HL:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_A_HLptrInc:
                throw LR35902ExecutionError.instructionNotImplemented
            case .dec_HL:
                throw LR35902ExecutionError.instructionNotImplemented
            case .inc_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .dec_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_L_d8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .cpl:
                try cpl()
            case .jr_nc_s8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_sp_d16:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_HLptrDec_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .inc_SP:
                throw LR35902ExecutionError.instructionNotImplemented
            case .inc_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .dec_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_HLptr_d8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .scf:
                try scf()
            case .jr_C_s8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .add_HL_SP:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_A_HLptrDec:
                throw LR35902ExecutionError.instructionNotImplemented
            case .dec_SP:
                throw LR35902ExecutionError.instructionNotImplemented
            case .inc_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .dec_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_A_d8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ccf:
                try ccf()
            case .ld_B_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_B_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_B_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_B_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_B_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_B_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_B_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_B_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_C_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_C_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_C_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_C_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_C_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_C_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_C_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_C_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_D_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_D_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_D_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_D_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_D_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_D_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_D_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_D_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_E_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_E_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_E_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_E_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_E_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_E_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_E_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_E_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_H_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_H_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_H_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_H_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_H_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_H_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_H_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_H_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_L_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_L_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_L_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_L_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_L_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_L_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_L_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_L_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_HLptr_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_HLptr_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_HLptr_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_HLptr_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_HLptr_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_HLptr_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .halt:
                try halt()
            case .ld_HLptr_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_A_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_A_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_A_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_A_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_A_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_A_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_A_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_A_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .add_A_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .add_A_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .add_A_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .add_A_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .add_A_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .add_A_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .add_A_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .add_A_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .adc_A_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .adc_A_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .adc_A_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .adc_A_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .adc_A_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .adc_A_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .adc_A_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .adc_A_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sub_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sub_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sub_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sub_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sub_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sub_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sub_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sub_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sbc_A_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sbc_A_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sbc_A_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sbc_A_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sbc_A_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sbc_A_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sbc_A_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sbc_A_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .and_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .and_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .and_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .and_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .and_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .and_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .and_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .and_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .xor_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .xor_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .xor_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .xor_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .xor_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .xor_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .xor_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .xor_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .or_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .or_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .or_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .or_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .or_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .or_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .or_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .or_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .cp_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .cp_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .cp_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .cp_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .cp_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .cp_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .cp_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .cp_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ret_nz:
                throw LR35902ExecutionError.instructionNotImplemented
            case .pop_BC:
                throw LR35902ExecutionError.instructionNotImplemented
            case .jp_nz_a16:
                throw LR35902ExecutionError.instructionNotImplemented
            case .jp_a16:
                throw LR35902ExecutionError.instructionNotImplemented
            case .call_nz_a16:
                throw LR35902ExecutionError.instructionNotImplemented
            case .push_BC:
                throw LR35902ExecutionError.instructionNotImplemented
            case .add_A_d8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rst_0:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ret_z:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ret:
                throw LR35902ExecutionError.instructionNotImplemented
            case .jp_z_a16:
                throw LR35902ExecutionError.instructionNotImplemented
            case .cb_prefix:
                throw LR35902ExecutionError.instructionNotImplemented
            case .call_z_a16:
                throw LR35902ExecutionError.instructionNotImplemented
            case .call_a16:
                throw LR35902ExecutionError.instructionNotImplemented
            case .adc_A_d8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rst_1:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ret_nc:
                throw LR35902ExecutionError.instructionNotImplemented
            case .pop_DE:
                throw LR35902ExecutionError.instructionNotImplemented
            case .jp_nc_a16:
                throw LR35902ExecutionError.instructionNotImplemented
            case .call_nc_a16:
                throw LR35902ExecutionError.instructionNotImplemented
            case .push_DE:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sub_d8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rst_2:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ret_c:
                throw LR35902ExecutionError.instructionNotImplemented
            case .reti:
                throw LR35902ExecutionError.instructionNotImplemented
            case .jp_c_a16:
                throw LR35902ExecutionError.instructionNotImplemented
            case .call_c_a16:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sbc_A_d8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rst_3:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_a8ptr_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .pop_HL:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_Cptr_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .push_HL:
                throw LR35902ExecutionError.instructionNotImplemented
            case .and_d8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rst_4:
                throw LR35902ExecutionError.instructionNotImplemented
            case .add_SP_s8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .jp_HL:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_a16ptr_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .xor_d8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rst_5:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_A_a8ptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .pop_AF:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_A_Cptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .di:
                try di()
            case .push_AF:
                throw LR35902ExecutionError.instructionNotImplemented
            case .or_d8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rst_6:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_HL_SP_plus_s8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_SP_HL:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ld_A_a16ptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .ei:
                try ei()
            case .cp_d8:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rst_7:
                throw LR35902ExecutionError.instructionNotImplemented
        }
    }

    func evaluate(_ instruction: LR35902Instruction16Bit) throws {
        switch instruction {
            case .rlc_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rlc_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rlc_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rlc_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rlc_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rlc_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rlc_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rlc_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rrc_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rrc_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rrc_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rrc_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rrc_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rrc_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rrc_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rrc_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rl_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rl_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rl_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rl_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rl_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rl_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rl_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rl_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rr_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rr_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rr_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rr_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rr_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rr_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rr_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .rr_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sla_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sla_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sla_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sla_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sla_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sla_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sla_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sla_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sra_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sra_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sra_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sra_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sra_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sra_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sra_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .sra_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .swap_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .swap_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .swap_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .swap_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .swap_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .swap_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .swap_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .swap_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .srl_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .srl_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .srl_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .srl_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .srl_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .srl_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .srl_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .srl_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_0_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_0_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_0_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_0_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_0_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_0_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_0_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_0_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_1_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_1_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_1_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_1_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_1_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_1_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_1_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_1_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_2_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_2_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_2_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_2_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_2_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_2_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_2_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_2_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_3_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_3_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_3_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_3_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_3_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_3_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_3_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_3_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_4_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_4_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_4_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_4_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_4_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_4_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_4_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_4_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_5_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_5_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_5_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_5_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_5_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_5_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_5_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_5_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_6_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_6_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_6_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_6_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_6_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_6_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_6_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_6_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_7_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_7_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_7_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_7_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_7_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_7_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_7_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .bit_7_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_0_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_0_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_0_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_0_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_0_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_0_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_0_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_0_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_1_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_1_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_1_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_1_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_1_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_1_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_1_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_1_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_2_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_2_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_2_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_2_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_2_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_2_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_2_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_2_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_3_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_3_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_3_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_3_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_3_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_3_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_3_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_3_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_4_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_4_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_4_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_4_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_4_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_4_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_4_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_4_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_5_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_5_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_5_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_5_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_5_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_5_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_5_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_5_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_6_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_6_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_6_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_6_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_6_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_6_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_6_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_6_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_7_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_7_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_7_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_7_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_7_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_7_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_7_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .res_7_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_0_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_0_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_0_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_0_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_0_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_0_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_0_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_0_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_1_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_1_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_1_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_1_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_1_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_1_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_1_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_1_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_2_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_2_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_2_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_2_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_2_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_2_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_2_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_2_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_3_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_3_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_3_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_3_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_3_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_3_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_3_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_3_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_4_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_4_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_4_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_4_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_4_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_4_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_4_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_4_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_5_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_5_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_5_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_5_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_5_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_5_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_5_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_5_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_6_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_6_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_6_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_6_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_6_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_6_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_6_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_6_A:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_7_B:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_7_C:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_7_D:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_7_E:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_7_H:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_7_L:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_7_HLptr:
                throw LR35902ExecutionError.instructionNotImplemented
            case .set_7_A:
                throw LR35902ExecutionError.instructionNotImplemented
        }
    }
}
